server:
  port: 8286

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/meharshitjain/microservices-using-springboot
          clone-on-start: true
